"""add article

Revision ID: 41ffd3aafc90
Revises: e32426d3e862
Create Date: 2016-10-29 21:38:24.352000

"""

# revision identifiers, used by Alembic.
revision = '41ffd3aafc90'
down_revision = 'e32426d3e862'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('visitNum', sa.Integer(), nullable=True),
    sa.Column('updatedTime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    ### end Alembic commands ###
