"""change group

Revision ID: 5b7e323cd9af
Revises: acc7a5fd9100
Create Date: 2016-10-29 15:32:08.436000

"""

# revision identifiers, used by Alembic.
revision = '5b7e323cd9af'
down_revision = 'acc7a5fd9100'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('about', sa.Text(), nullable=False))
    op.add_column('groups', sa.Column('logo', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'logo')
    op.drop_column('groups', 'about')
    ### end Alembic commands ###
